SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER, USED_GOODS_BOARD
GROUP BY USER_ID, WRITER_ID
HAVING USER_ID = WRITER_ID AND COUNT(WRITER_ID) >= 3
ORDER BY USER_ID DESC;