SELECT FLAVOR FROM FIRST_HALF
INNER JOIN (
    SELECT F.FLAVOR AS TOTAL_FLAVOR, SUM(F.TOTAL_ORDER + J.TOTAL_ORDER) AS TOTAL FROM FIRST_HALF AS F
    INNER JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) AS J
    ON J.FLAVOR = F.FLAVOR
    GROUP BY F.FLAVOR
) AS TOTAL_TABLE
WHERE TOTAL_FLAVOR = FLAVOR
ORDER BY TOTAL DESC
LIMIT 3;