SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO AS I
INNER JOIN ITEM_TREE AS T
ON I.ITEM_ID = T.ITEM_ID
INNER JOIN ITEM_INFO AS N
ON T.PARENT_ITEM_ID = N.ITEM_ID
WHERE N.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC;